apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrykme9469.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
        env:
          - name: SQL_PASSWORD
            value: "Password@123"
          - name: SQL_SERVER
            value: "sqlserverkme9469.database.windows.net"
          - name: SQL_USER
            value: "sqladminkMe9469"
          - name: SQL_DBNAME
            value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  selector:
    app: user-java
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
